export const SET_CUSTOMER_ID: "SET_CUSTOMER_ID" = "SET_CUSTOMER_ID";
export const SET_CUSTOMER_ID_SUCCESS: "SET_CUSTOMER_ID_SUCCESS" =
  "SET_CUSTOMER_ID_SUCCESS";
export const SET_CUSTOMER_ID_FAILED: "SET_CUSTOMER_ID_FAILED" =
  "SET_CUSTOMER_ID_FAILED";
